import { Box } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Button from "src/components/Button";
import View from "src/components/View";
import withProtected from "src/hoc/withProtected";

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sample | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <View title="Projects">
        <View.Body variant="standard">
          <Box sx={{ mb: 2 }}>
            <Link href="/projects/create-project">
              <Button>New Project</Button>
            </Link>
          </Box>
          <Link href="/projects/23234234234">
            <Button>Project 23234234234</Button>
          </Link>
        </View.Body>
      </View>
    </>
  );
};

export default withProtected({ redirect: "/login " })(Projects);
