import type { NextPage } from "next";
import Head from "next/head";
import { Typography } from "@mui/material";
import View from "src/components/View";
import withProtected from "src/hoc/withProtected";

const Calendar: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sample | Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <View title="Calendar">
        <View.Body>
          <Typography>...</Typography>
        </View.Body>
      </View>
    </>
  );
};

export default withProtected({ redirect: "/login" })(Calendar);
