import Head from "next/head";
import type { NextPage } from "next";
import { useActor, useSelector } from "@xstate/react";

import { useApp } from "src/contexts/AppContext";
import View from "src/components/View";
import Button from "src/components/Button";
import withProtected from "src/hoc/withProtected";

const Dashboard: NextPage = () => {
  const { appService } = useApp();
  const [state, send] = useActor(appService);

  // Temporary
  const authenticated = useSelector(appService, (state) =>
    state.matches({ authentication: { init: "authenticated" } })
  );

  return (
    <>
      <Head>
        <title>Sample | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <View title="Home">
        <View.Body variant="standard">
          {authenticated && (
            <Button
              onClick={() =>
                send({
                  type: "AUTH_LOGOUT",
                })
              }
            >
              Logout
            </Button>
          )}
        </View.Body>
      </View>
    </>
  );
};

export default withProtected({ redirect: "/login" })(Dashboard);
